Repository magyar-matyas/Project_2_10A, pull requests merged in 2023-06, with the labels that each got.

#106 Kulacs kristof/issue56
  main.py
Labels: karakterek

#108 karakterek,, kib*szott szar github
  akasztottak/lvl14/h0.png
  akasztottak/lvl14/h1.png
  akasztottak/lvl14/h2.png
  akasztottak/lvl14/h3.png
  akasztottak/lvl14/h4.png
  akasztottak/lvl14/h5.png
  akasztottak/lvl14/h6.png
  akasztottak/lvl14/h7.png
  akasztottak/lvl14/h8.png
  akasztottak/lvl15/h0.png
  akasztottak/lvl15/h1.png
  akasztottak/lvl15/h2.png
  akasztottak/lvl15/h3.png
  akasztottak/lvl15/h4.png
  akasztottak/lvl15/h5.png
  akasztottak/lvl15/h6.png
  akasztottak/lvl15/h7.png
  akasztottak/lvl15/h8.png
  akasztottak/lvl16/h0.png
  akasztottak/lvl16/h1.png
  akasztottak/lvl16/h2.png
  akasztottak/lvl16/h3.png
  akasztottak/lvl16/h4.png
  akasztottak/lvl16/h5.png
  akasztottak/lvl16/h6.png
  akasztottak/lvl16/h7.png
  akasztottak/lvl16/h8.png
  akasztottak/lvl17/h0.png
  akasztottak/lvl17/h1.png
  akasztottak/lvl17/h2.png
  akasztottak/lvl17/h3.png
  akasztottak/lvl17/h4.png
  akasztottak/lvl17/h5.png
  akasztottak/lvl17/h6.png
  akasztottak/lvl17/h7.png
  akasztottak/lvl17/h8.png
  akasztottak/lvl18/h0.png
  akasztottak/lvl18/h1.png
  akasztottak/lvl18/h2.png
  akasztottak/lvl18/h3.png
  akasztottak/lvl18/h4.png
  akasztottak/lvl18/h5.png
  akasztottak/lvl18/h6.png
  akasztottak/lvl18/h7.png
  akasztottak/lvl18/h8.png
  akasztottak/lvl19/h0.png
  akasztottak/lvl19/h1.png
  akasztottak/lvl19/h2.png
  akasztottak/lvl19/h3.png
  akasztottak/lvl19/h4.png
  akasztottak/lvl19/h5.png
  akasztottak/lvl19/h6.png
  akasztottak/lvl19/h7.png
  akasztottak/lvl19/h8.png
Labels: karakterek

#110 minden is ,fkivan :///
  Corpses.py
  Hangman.py
  __pycache__/Corpses.cpython-310.pyc
  __pycache__/Gombok.cpython-310.pyc
  __pycache__/Hangman.cpython-310.pyc
  __pycache__/Szavak.cpython-310.pyc
  main.py
  szavak.txt
Labels: bug, documentation, duplicate, enhancement, help wanted, good first issue, invalid, question, wontfix, szavak, karakterek, programkód(funkcionalitás), visual

#111 lvl2
  akasztottak/lvl1/h0.png
  akasztottak/lvl1/h1.png
  akasztottak/lvl1/h2.png
  akasztottak/lvl1/h3.png
  akasztottak/lvl1/h4.png
  akasztottak/lvl1/h5.png
  akasztottak/lvl1/h6.png
  akasztottak/lvl1/h7.png
  akasztottak/lvl1/h8.png
  akasztottak/lvl2/h0.png
  akasztottak/lvl2/h1.png
  akasztottak/lvl2/h2.png
  akasztottak/lvl2/h3.png
  akasztottak/lvl2/h4.png
  akasztottak/lvl2/h5.png
  akasztottak/lvl2/h6.png
  akasztottak/lvl2/h7.png
  akasztottak/lvl2/h8.png
Labels: karakterek

#112 lvl3
  akasztottak/lvl3/h0.png
  akasztottak/lvl3/h1.png
  akasztottak/lvl3/h2.png
  akasztottak/lvl3/h3.png
  akasztottak/lvl3/h4.png
  akasztottak/lvl3/h5.png
  akasztottak/lvl3/h6.png
  akasztottak/lvl3/h7.png
  akasztottak/lvl3/h8.png
Labels: karakterek

#113 lvl4
  akasztottak/lvl4/h0.png
  akasztottak/lvl4/h1.png
  akasztottak/lvl4/h2.png
  akasztottak/lvl4/h3.png
  akasztottak/lvl4/h4.png
  akasztottak/lvl4/h5.png
  akasztottak/lvl4/h6.png
  akasztottak/lvl4/h7.png
  akasztottak/lvl4/h8.png
Labels: karakterek

#125 ppt kész
  Akasztófa Projekt.pptm
Labels: documentation
