Repository magyar-matyas/Project_2_10A, pull requests merged in 2023-05, with the labels that each got.

#5 main.py +launch json
  .vscode/launch.json
  main.py
Labels: programkód(funkcionalitás)

#7 pygame, screen
  main.py
Labels: programkód(funkcionalitás)

#9 főmenü alap
  main.py
Labels: visual

#11 osztaly + txt
  Szavak.py
  szavak.txt
Labels: szavak, programkód(funkcionalitás)

#20 szobeolvasas
  Hangman.py
Labels: programkód(funkcionalitás)

#21 done
  Hangman.py
Labels: programkód(funkcionalitás)

#22 emberek beolvasas
  Hangman.py
Labels: programkód(funkcionalitás)

#23 19 vonalak kiírása függvény
  Hangman.py
Labels: programkód(funkcionalitás)

#29 gombok függvény
  Hangman.py
Labels: programkód(funkcionalitás)

#30 guess fuggveny
  Hangman.py
Labels: programkód(funkcionalitás)

#32 27 akasztofa fuggveny pt2
  Hangman.py
Labels: programkód(funkcionalitás)

#33 level end screen/ next level működés
  Hangman.py
Labels: programkód(funkcionalitás)

#50 34 akasztofa fuggveny meghivas + level score mentés
  main.py
  score.txt
  szavak.txt
Labels: programkód(funkcionalitás), visual

#81 exit gomb
  __pycache__/Corpses.cpython-310.pyc
  __pycache__/Gombok.cpython-310.pyc
  __pycache__/Hangman.cpython-310.pyc
  __pycache__/Szavak.cpython-310.pyc
  main.py
Labels: visual

#82 hoovers
  Gombok.py
  Hangman.py
  main.py
Labels: visual

#83 custom
  custom.txt
  main.py
Labels: programkód(funkcionalitás)

#84 fixed
  Corpses.py
  Hangman.py
Labels: programkód(funkcionalitás)

#85 főmenü + highscore
  Hangman.py
  highscore.txt
  képek/pixil-frame-1.png
  main.py
Labels: enhancement, visual

#86 4-betűs-szavak-kész
  szavak.txt
Labels: szavak
